// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorTabsMenu.Models;

public partial class Country
{
    [Key]
    public int Id { get; set; }

    [StringLength(2)]
    public string CountryCode { get; set; } = null!;

    [StringLength(50)]
    public string CountryName { get; set; } = null!;

    [StringLength(6)]
    public string CountryPrefix { get; set; } = null!;

    public int AdminInstid { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CurrencySymbol { get; set; } = null!;

    [StringLength(100)]
    public string? CurrencyName { get; set; }

    public int? SurveyYear { get; set; }

    public int? SurveyLastYear { get; set; }

    [StringLength(15)]
    public string? SurveyDbYear { get; set; }

    [StringLength(15)]
    public string? SurveyDbLastYear { get; set; }

    [StringLength(15)]
    public string? SurveyDbVerifyYear { get; set; }

    [Column("opendate", TypeName = "datetime")]
    public DateTime? Opendate { get; set; }

    [Column("closedate", TypeName = "datetime")]
    public DateTime? Closedate { get; set; }
}