// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorTabsMenu.Models;

public partial class DataDictionaryItem
{
    [Key]
    public Guid Id { get; set; }

    public int? Sequence { get; set; }

    public string? Topic { get; set; }

    [Column("Tab_new")]
    public int? TabNew { get; set; }

    public int? TabNumber { get; set; }

    [StringLength(10)]
    public string? QuestionNumber { get; set; }

    public string? ReportingPeriod { get; set; }

    public string? ColumnName { get; set; }

    public string? ColumnNameStatus { get; set; }

    public string? DataType { get; set; }

    public string? PocoType { get; set; }

    public string? Source { get; set; }

    public string? Validate { get; set; }

    public string? QuestionLabelText { get; set; }

    public string? QuestionText { get; set; }

    public string? HelpText { get; set; }

    public string? DefinedTerm { get; set; }

    public int? Answer2018 { get; set; }

    public int? Answer2019 { get; set; }

    [StringLength(2)]
    public string? CountryCode { get; set; }

    public int? IsDisplayed { get; set; }

    [StringLength(256)]
    public string? DisplayTemplate { get; set; }
}